- name: testing
  hosts: checking
  become: yes
  tasks:
  - name: Install ansible
    ansible.builtin.package: 
      name: ansible
      state: present

  - name: Clone GitHub repository
    git:
      repo: "https://github.com/SomeshwarSangaraju/ansible_practice.git"
      dest: /home/ec2-user
      version: main
      force: yes
