- name: Create catalogue playbook
  hosts: catalogue
  become: yes
  tasks:
  - name: Disabling nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: enabling nodejs
    ansible.builtin.package:
      name: nodejs:20
      state: present
    
  - name: Install node.js
    community.general.npm:
      name: nodejs
      path: /app

  - name: System user
    ansible.builtin.user:
      name: roboshop
      comment: "roboshop system user"
      home: /app
      shell: /sbin/nologin
  
  - name: Create directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip

  - name: Change directory
    ansible.builtin.file:
      path: /app
      state: present

  - name: Install npm
    community.general.npm:
      name: npm
      path: /app

  - name: Adding catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
    
  - name: Starting and enabling service
    ansible.builtin.service:
      state: started
      enabled: yes
      demon_reload: true

  
  
