- name: create mongodb instance
  hosts: mongodb
  become: yes
  tasks:
  - name: Copying mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing mongodb
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: Starting and enabling mongodb
    ansible.builtin.service:
      state: started
      enabled: true

  # - name: Allow remote Mongodb connections
  #   ansible.builtin.lineinfile:
  #     path: /etc/mongod.conf
  #     regexp: 127.0.0.1
  #     line: 0.0.0.0
  - name: allow remote connection
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Restart MySQL
    ansible.builtin.service:
      name: mysql
      state: restarted
